debug: Increase judgment in workflows
Signed-off-by: prslc <prslc113@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,22 +17,31 @@ jobs:
         run: |
           mkdir kpm
           cd kpm
+          
           KernelPatch_LATEST_TAG=$(gh release list -R bmax121/KernelPatch --limit 1 | awk '{print $1}')
-          gh release download "$KernelPatch_LATEST_TAG" -R bmax121/KernelPatch --pattern "kpimg-linux"
-          gh release download "$KernelPatch_LATEST_TAG" -R bmax121/kernelPatch --pattern "kptools-android"
+          if [ -z "$KernelPatch_LATEST_TAG" ]; then
+            echo "Error: No release found for bmax121/KernelPatch"
+            exit 1
+          fi
+          gh release download "$KernelPatch_LATEST_TAG" -R bmax121/KernelPatch --pattern "kpimg-linux" || exit 1
+          gh release download "$KernelPatch_LATEST_TAG" -R bmax121/kernelPatch --pattern "kptools-android" || exit 1
 
           KPM_LATEST_TAG=$(gh release list -R lzghzr/APatch_kpm  --limit 1 | awk '{print $1}')
-          gh release download "$KPM_LATEST_TAG" -R lzghzr/APatch_kpm --pattern "re_kernel*.kpm"
+          if [ -z "$KPM_LATEST_TAG" ]; then
+            echo "Error: No release found for lzghzr/APatch_kpm"
+            exit 1
+          fi
+          gh release download "$KPM_LATEST_TAG" -R lzghzr/APatch_kpm --pattern "re_kernel*.kpm" || exit 1
           mv re_kernel_*_network.kpm Re-Kernel_network.kpm
           find . -type f -name "re_kernel_*.kpm" -exec mv {} Re-Kernel.kpm \;
 
-          cd ../
           MAGISK_LATEST_TAG=$(gh release list -R topjohnwu/Magisk  --limit 1 | awk '{print $1}')
-          gh release download "$MAGISK_LATEST_TAG" -R topjohnwu/Magisk --pattern "Magisk-*.apk"
-          mkdir magisk_unpack
-          unzip Magisk-*.apk -d magisk_unpack
-          cp magisk_unpack/lib/arm64-v8a/libmagiskboot.so .
-          rm -rf Magisk-*.apk magisk_unpack
+          if [ -z "$MAGISK_LATEST_TAG" ]; then
+            echo "Error: No release found for topjohnwu/Magisk"
+            exit 1
+          fi
+          gh release download "$MAGISK_LATEST_TAG" -R topjohnwu/Magisk --pattern "Magisk-*.apk" || exit 1
+
 
 
       - name: Repack ReKPatch
